name: ai-content-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - flask==3.1.2
      - werkzeug==3.1.3
      - jinja2==3.1.6
      - itsdangerous==2.2.0
      - blinker==1.9.0

      - python-dotenv==1.1.1
      - sqlalchemy==2.0.36
      - psycopg2-binary==2.9.10

      - apscheduler==3.10.4
      - tqdm==4.67.1
      - requests==2.32.5
      - python-dateutil==2.9.0.post0

      - openai==1.42.0
      - httpx==0.27.2
      - httpcore==1.0.9
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - annotated-types==0.7.0

      - python-telegram-bot==21.6
      - gTTS==2.5.4

      - pillow==11.3.0
      - numpy==2.3.2
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - moviepy==2.2.1
      - yt-dlp==2025.9.5

      - cryptography==43.0.3

      # Payments
      - stripe==11.3.0
      - paypalhttp==1.0.1
      - paypal-checkout-serversdk==1.0.3
      - razorpay==1.4.2
      - cashfree-sdk==0.1.3
